parameters:
#    base_user.example.class: Base\UserBundle\Example

services:
#    base_user.example:
#        class: %base_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
